# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z007sclg225-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/hdl_projects/MiniZed_full/MiniZed_full.cache/wt [current_project]
set_property parent.project_path C:/hdl_projects/MiniZed_full/MiniZed_full.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:minized:part0:1.0 [current_project]
set_property ip_repo_paths c:/hdl_projects/digilent [current_project]
set_property ip_output_repo c:/hdl_projects/MiniZed_full/MiniZed_full.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/hdl_projects/MiniZed_full/MiniZed_full.srcs/sources_1/imports/Lab3_hw_full/wireless_mgr.vhd
  C:/hdl_projects/MiniZed_full/MiniZed_full.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.vhd
}
add_files C:/hdl_projects/MiniZed_full/MiniZed_full.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all c:/hdl_projects/MiniZed_full/MiniZed_full.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/MiniZed_full/MiniZed_full.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_50M_0/design_1_rst_ps7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/MiniZed_full/MiniZed_full.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_50M_0/design_1_rst_ps7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/MiniZed_full/MiniZed_full.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_50M_0/design_1_rst_ps7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/MiniZed_full/MiniZed_full.srcs/sources_1/bd/design_1/ip/design_1_axi_quad_spi_0_0/design_1_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/MiniZed_full/MiniZed_full.srcs/sources_1/bd/design_1/ip/design_1_axi_quad_spi_0_0/design_1_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/MiniZed_full/MiniZed_full.srcs/sources_1/bd/design_1/ip/design_1_axi_quad_spi_0_0/design_1_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/MiniZed_full/MiniZed_full.srcs/sources_1/bd/design_1/ip/design_1_axi_quad_spi_0_0/design_1_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/MiniZed_full/MiniZed_full.srcs/sources_1/bd/design_1/ip/design_1_axi_vdma_0_0/design_1_axi_vdma_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/MiniZed_full/MiniZed_full.srcs/sources_1/bd/design_1/ip/design_1_axi_vdma_0_0/design_1_axi_vdma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/MiniZed_full/MiniZed_full.srcs/sources_1/bd/design_1/ip/design_1_axi_vdma_0_0/design_1_axi_vdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/MiniZed_full/MiniZed_full.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/MiniZed_full/MiniZed_full.srcs/sources_1/bd/design_1/ip/design_1_v_axi4s_vid_out_0_0/design_1_v_axi4s_vid_out_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/MiniZed_full/MiniZed_full.srcs/sources_1/bd/design_1/ip/design_1_v_axi4s_vid_out_0_0/design_1_v_axi4s_vid_out_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/MiniZed_full/MiniZed_full.srcs/sources_1/bd/design_1/ip/design_1_ila_0_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/MiniZed_full/MiniZed_full.srcs/sources_1/bd/design_1/ip/design_1_ila_0_0/design_1_ila_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/MiniZed_full/MiniZed_full.srcs/sources_1/bd/design_1/ip/design_1_ila_0_1/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/MiniZed_full/MiniZed_full.srcs/sources_1/bd/design_1/ip/design_1_ila_0_1/design_1_ila_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/MiniZed_full/MiniZed_full.srcs/sources_1/bd/design_1/ip/design_1_v_tc_0_0/design_1_v_tc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/MiniZed_full/MiniZed_full.srcs/sources_1/bd/design_1/ip/design_1_v_tc_0_0/design_1_v_tc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/MiniZed_full/MiniZed_full.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_50M_1/design_1_rst_ps7_0_50M_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/MiniZed_full/MiniZed_full.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_50M_1/design_1_rst_ps7_0_50M_1.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/MiniZed_full/MiniZed_full.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_50M_1/design_1_rst_ps7_0_50M_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/MiniZed_full/MiniZed_full.srcs/sources_1/bd/design_1/ip/design_1_axis_subset_converter_0_0/design_1_axis_subset_converter_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/MiniZed_full/MiniZed_full.srcs/sources_1/bd/design_1/ip/design_1_ila_1_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/MiniZed_full/MiniZed_full.srcs/sources_1/bd/design_1/ip/design_1_ila_1_0/design_1_ila_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/MiniZed_full/MiniZed_full.srcs/sources_1/bd/design_1/ip/design_1_ila_0_2/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/MiniZed_full/MiniZed_full.srcs/sources_1/bd/design_1/ip/design_1_ila_0_2/design_1_ila_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/MiniZed_full/MiniZed_full.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/hdl_projects/MiniZed_full/MiniZed_full.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/hdl_projects/MiniZed_full/MiniZed_full.srcs/sources_1/bd/design_1/design_1_ooc.xdc]
set_property is_locked true [get_files C:/hdl_projects/MiniZed_full/MiniZed_full.srcs/sources_1/bd/design_1/design_1.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/hdl_projects/MiniZed_full/MiniZed_full.srcs/constrs_1/imports/Lab3_hw_full/minized_pins.xdc
set_property used_in_implementation false [get_files C:/hdl_projects/MiniZed_full/MiniZed_full.srcs/constrs_1/imports/Lab3_hw_full/minized_pins.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top design_1_wrapper -part xc7z007sclg225-1


write_checkpoint -force -noxdef design_1_wrapper.dcp

catch { report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb }
